version: "3"

services:
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"

  app:
    build: .
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 80"
    ports:
      - "80:80"
    depends_on:
    - mongo_db